PREFIX mo: <http://mlu.marklogic.com/ontology/>

SELECT ?country ?min
FROM <http://mlu.marklogic.com/populations>
WHERE {
        {
          SELECT (MIN(?pop) as ?min)
          WHERE {?country mo:population ?pop}
        }
        {
          ?country mo:population ?pop . ?country mo:population ?min
        }
}
