PREFIX rsrc: <http://mydomain.org/resource/>
PREFIX onto: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?name
FROM <http://mlu.marklogic.com/family-tree>
WHERE {rsrc:Mary onto:child/foaf:name | onto:child/onto:child/foaf:name ?name} 
