PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX onto: <http://dbpedia.org/ontology/>

SELECT ?s ?o
WHERE {
        {?s rdf:type onto:Bird}
       UNION
        {?s rdf:type onto:Fish}
       OPTIONAL {?s <http://www.w3.org/2000/01/rdf-schema#comment> ?o}
              }
