PREFIX rsrc: <http://dbpedia.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?o
FROM <http://mlu.marklogic.com/animals>
WHERE {rsrc:Kangaroo rdfs:comment ?o . FILTER (lang(?o) = "en")}
